export const FETCH_MAIN_DATA='FETCH_MAIN_DATA'

export const FETCH_MAIN_VO='FETCH_MAIN_VO'



//cdlp
export const FETCH_CDLP_LIST='FETCH_CDLP_LIST'
//@getMapping
export const FETCH_CDLP_FIND='FETCH_CDLP_FIND'
export const FETCH_CDLP_DETAIL='FETCH_CDLP_DETAIL'



//bd
export const FETCH_BD_LIST='FETCH_BD_LIST'

export const FETCH_BD_DETAIL='FETCH_BD_DETAIL'

export const BOARD_LIST='BOARD_LIST'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_DETAIL='BOARD_DETAIL'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_UPDATE_DATA='BOARD_UPDATE_DATA'
export const BOARD_DELETE='BOARD_DELETE'